"""Application-owned seams for isolated character conversation."""
from pathlib import Path
from typing import Any, Protocol

class CharacterChatRepositoryPort(Protocol):
    def list(self, project_root: Path) -> list[dict[str, Any]]: ...
    def read(self, project_root: Path, session_id: str) -> dict[str, Any]: ...
    def save(self, project_root: Path, session: dict[str, Any]) -> None: ...
    def cards(self, project_root: Path) -> list[dict[str, Any]]: ...

class CharacterConversationPort(Protocol):
    def draft_card(self, project_root: Path, *, guidance: str, context: dict[str, Any]) -> dict[str, Any]: ...
    def reply(self, project_root: Path, *, system: str, history: list[tuple[str, str]],
              prompt: str, timeout: int) -> str: ...

class CharacterChatArchivePort(Protocol):
    def list(self, project_root: Path, *, prefix: str, cursor: int) -> dict[str, Any]: ...
    def read(self, project_root: Path, path: str, *, offset: int) -> dict[str, Any]: ...
    def freeze(self, project_root: Path, attachments: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

