"""Studio-owned adaptive planning above the formal Engine lifecycle."""

from .agent_transport import (
    OrchestrationAgentResponse,
    OrchestrationAgentTransport,
    RuntimeOrchestrationAgentTransport,
)
from .activation import (
    activate_persisted_revision,
    assisted_activate_persisted_revision,
    authorize_persisted_revision,
)
from .active_plan import ActivePlanLoader, ActiveScenePlan
from .bundles import (
    BundleTemplate,
    BundleViolation,
    ExecutionBundle,
    bundle_template,
    bundle_template_catalog,
    bundle_violations,
    compile_bundles,
)
from .candidate import MACHINE_OWNED_FIELDS, parse_plan_candidate
from .chapter_binding import (
    ChapterWindowPolicy,
    chapter_window_policy,
    project_chapter_candidate_parameters,
)
from .chapter_facts import (
    ChapterFactViolation,
    ChapterPlanningFacts,
    ScenePlanningFact,
    chapter_facts_violations,
    scene_order,
    scene_risk_values,
)
from .chapter_facts_io import load_chapter_planning_facts
from .chapter_horizon import (
    ChapterHorizonProjection,
    ChapterHorizonShadowEvaluation,
    ChapterHorizonViolation,
    evaluate_chapter_horizon_shadow,
    project_chapter_horizon,
)
from .chapter_shadow import (
    ChapterPlanShadowEvaluation,
    evaluate_chapter_plan_shadow,
    evaluate_chapter_plan_shadow_from_project,
)
from .checkpoint import (
    ChapterCheckpoint,
    CheckpointViolation,
    checkpoint_matches,
    checkpoint_newer,
    checkpoint_violations,
)
from .compiler import PlanCompilationError, compile_plan, compiled_graph_digest
from .compiler_registry import CompilerRegistry
from .constitution import OrchestrationConstitution, constitution_v1
from .contracts import (
    CANDIDATE_SCHEMA,
    COMPILED_GRAPH_SCHEMA,
    PLAN_PATCH_SCHEMA,
    PLAN_SCHEMA,
    CompiledTaskGraph,
    CompiledTaskNode,
    CreativeExecutionPlan,
    CreativeExecutionPlanCandidate,
    FreedomBudget,
    PlanLifecycleStatus,
    PlanScopeKind,
    ReplanTrigger,
    RevisionPolicy,
    RoleplayDepth,
    SceneFallbackLevel,
    TaskBinding,
    to_primitive,
)
from .patch import (
    PlanPatchDiff,
    ScenePlanPatchEvaluation,
    creative_plan_digest,
    evaluate_scene_plan_patch,
    parse_scene_plan_patch,
)
from .risk import (
    SceneRiskFacts,
    SceneRiskLevel,
    SceneRiskProfile,
    SceneRiskViolation,
    build_scene_risk_profile,
    effective_risk_level,
    machine_minimum_risk_level,
    scene_risk_violations,
)
from .rolling_horizon import (
    MAX_HORIZON_SIZE,
    MIN_HORIZON_SIZE,
    RollingHorizonViolation,
    RollingHorizonWindow,
    build_rolling_horizon,
    rolling_horizon_violations,
)
from .scene_binding import (
    SceneExecutionPolicy,
    SceneTaskPlanBinding,
    bind_scene_task,
)
from .defaults import DefaultPlanFactory
from .lint import PlanIssue, PlanIssueSeverity, PlanLintContext, PlanLintResult, lint_plan
from .normalizer import NormalizationContext, candidate_digest, normalize_plan_candidate
from .persistence import (
    OrchestrationAuditArtifacts,
    persist_shadow_revision,
    read_verified_revision_payloads,
    verify_persisted_revision,
)
from .project_fingerprint import planning_project_fingerprint
from .progress import (
    ProgressFingerprint,
    ProgressFingerprintInput,
    ProgressFingerprintViolation,
    no_progress_detected,
    progress_fingerprint,
    progress_input_violations,
)
from .resource_gate import (
    AdmissionPlan,
    ParallelGroup,
    ResourceGateViolation,
    admission_plan,
)
from .recovery import (
    RecoveryDecision,
    RecoveryStep,
    RecoveryViolation,
    recovery_step,
    recovery_violations,
)
from .replan import (
    ReplanBudgetState,
    ReplanBudgetViolation,
    ReplanDecision,
    replan_allowed,
    replan_budget_violations,
)
from .simulator import (
    FormalTaskObservation,
    FormalTaskStatus,
    PlanSimulationContext,
    PlanSimulationResult,
    SimulatedNode,
    SimulatedResourceConflict,
    simulate_plan,
)
from .settings import (
    OrchestrationMode,
    OrchestrationSettings,
    StrategyPreset,
    orchestration_settings,
)
from .service import ShadowOrchestrationService
from .shadow_run import (
    FixedRouteComparison,
    ShadowOrchestrationResult,
    ShadowPlanningInput,
)
from .profiles import (
    OrchestrationAgentProfile,
    OrchestrationAgentRole,
    orchestration_profile,
)
from .plan_events import (
    CREATIVE_PLAN_EVENT_SCHEMA,
    CreativePlanEvent,
    CreativePlanEventType,
    completed_candidate_from_event,
    parse_creative_plan_event,
)
from .shadow import (
    ShadowPlanEvaluation,
    ShadowStageTiming,
    evaluate_completed_shadow_candidate,
    evaluate_shadow_candidate,
)
from .truth_partition import (
    AssertionKind,
    ProvenanceRef,
    TruthPartition,
    partition_can_satisfy_formal_gate,
)

__all__ = [
    "AssertionKind",
    "ActivePlanLoader",
    "ActiveScenePlan",
    "AdmissionPlan",
    "BundleTemplate",
    "BundleViolation",
    "CANDIDATE_SCHEMA",
    "COMPILED_GRAPH_SCHEMA",
    "ChapterFactViolation",
    "ChapterCheckpoint",
    "ChapterHorizonProjection",
    "ChapterHorizonShadowEvaluation",
    "ChapterHorizonViolation",
    "ChapterPlanShadowEvaluation",
    "ChapterPlanningFacts",
    "ChapterWindowPolicy",
    "CheckpointViolation",
    "MACHINE_OWNED_FIELDS",
    "MAX_HORIZON_SIZE",
    "MIN_HORIZON_SIZE",
    "PLAN_PATCH_SCHEMA",
    "PLAN_SCHEMA",
    "CompiledTaskGraph",
    "CompiledTaskNode",
    "CompilerRegistry",
    "CreativeExecutionPlan",
    "CreativeExecutionPlanCandidate",
    "CreativePlanEvent",
    "CreativePlanEventType",
    "CREATIVE_PLAN_EVENT_SCHEMA",
    "DefaultPlanFactory",
    "ExecutionBundle",
    "FixedRouteComparison",
    "FreedomBudget",
    "NormalizationContext",
    "OrchestrationMode",
    "OrchestrationAgentProfile",
    "OrchestrationAgentResponse",
    "OrchestrationAgentRole",
    "OrchestrationAgentTransport",
    "OrchestrationConstitution",
    "OrchestrationAuditArtifacts",
    "OrchestrationSettings",
    "ParallelGroup",
    "PlanIssue",
    "PlanIssueSeverity",
    "PlanCompilationError",
    "PlanLifecycleStatus",
    "PlanLintContext",
    "PlanLintResult",
    "PlanSimulationContext",
    "PlanSimulationResult",
    "PlanScopeKind",
    "ProgressFingerprint",
    "ProgressFingerprintInput",
    "ProgressFingerprintViolation",
    "ProvenanceRef",
    "ResourceGateViolation",
    "RecoveryDecision",
    "RecoveryStep",
    "RecoveryViolation",
    "ReplanBudgetState",
    "ReplanBudgetViolation",
    "ReplanDecision",
    "ReplanTrigger",
    "RevisionPolicy",
    "RoleplayDepth",
    "SceneExecutionPolicy",
    "SceneFallbackLevel",
    "ScenePlanningFact",
    "ScenePlanPatchEvaluation",
    "SceneTaskPlanBinding",
    "PlanPatchDiff",
    "RuntimeOrchestrationAgentTransport",
    "RollingHorizonViolation",
    "RollingHorizonWindow",
    "SceneRiskFacts",
    "SceneRiskLevel",
    "SceneRiskProfile",
    "SceneRiskViolation",
    "FormalTaskObservation",
    "FormalTaskStatus",
    "SimulatedNode",
    "SimulatedResourceConflict",
    "ShadowPlanEvaluation",
    "ShadowOrchestrationResult",
    "ShadowOrchestrationService",
    "ShadowPlanningInput",
    "ShadowStageTiming",
    "StrategyPreset",
    "TaskBinding",
    "TruthPartition",
    "compile_plan",
    "compiled_graph_digest",
    "creative_plan_digest",
    "candidate_digest",
    "constitution_v1",
    "evaluate_shadow_candidate",
    "evaluate_completed_shadow_candidate",
    "evaluate_scene_plan_patch",
    "activate_persisted_revision",
    "admission_plan",
    "assisted_activate_persisted_revision",
    "authorize_persisted_revision",
    "lint_plan",
    "normalize_plan_candidate",
    "orchestration_settings",
    "orchestration_profile",
    "parse_plan_candidate",
    "parse_scene_plan_patch",
    "bind_scene_task",
    "bundle_template",
    "bundle_template_catalog",
    "bundle_violations",
    "build_rolling_horizon",
    "build_scene_risk_profile",
    "chapter_facts_violations",
    "checkpoint_matches",
    "checkpoint_newer",
    "checkpoint_violations",
    "evaluate_chapter_horizon_shadow",
    "evaluate_chapter_plan_shadow",
    "evaluate_chapter_plan_shadow_from_project",
    "parse_creative_plan_event",
    "completed_candidate_from_event",
    "effective_risk_level",
    "machine_minimum_risk_level",
    "no_progress_detected",
    "project_chapter_horizon",
    "project_chapter_candidate_parameters",
    "progress_fingerprint",
    "progress_input_violations",
    "recovery_step",
    "recovery_violations",
    "replan_allowed",
    "replan_budget_violations",
    "partition_can_satisfy_formal_gate",
    "persist_shadow_revision",
    "planning_project_fingerprint",
    "read_verified_revision_payloads",
    "rolling_horizon_violations",
    "scene_order",
    "scene_risk_violations",
    "scene_risk_values",
    "chapter_window_policy",
    "compile_bundles",
    "load_chapter_planning_facts",
    "simulate_plan",
    "to_primitive",
    "verify_persisted_revision",
]
